version: "3.9"

mariadb:
  container_name: mariadb
  build: requirements/mariadb
  #image: mariadb
  env_file: .env
  ports:
    - 3306:3306
  networks:
    - inception
  volumes:
    - database:/var/lib/mysql
  restart: unless-stopped