FROM alpine:latest
RUN apk update

RUN apk add nginx openssl

CMD ["sh", "-c", "while true; do echo hello; sleep 1; done", "&&", "tail", "-f", "/dev/null"]
#     mkdir -p /run/nginx && \
#     openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/CN=localhost" && \
#     rm -rf /var/cache/apk/*

# COPY nginx.conf /etc/nginx/nginx.conf
# COPY html /usr/share/nginx/html

# EXPOSE 80 443

# CMD ["nginx", "-g", "daemon off;"]
